Industries = [
    "Accounting/Finance",
    "Advertising and Marketing",
    "Aerospace",
    "Architecture",
    "Business and Finance",
    "Chemical Engineering",
    "Civil Engineering",
    "Cybersecurity",
    "Data Analytics",
    "Education and Social Services",
    "Electrical Engineering",
    "Environmental Science",
    "Film and Media",
    "Finance and Investment",
    "Game Design and Development",
    "Health and Safety",
    "Healthcare and Medicine",
    "Human Resources",
    "Information Technology",
    "International Law",
    "Administrative Law",
    "Criminal Law",
    "Civil Law",
    "Legal",
    "Logistics and Supply Chain",
    "Marine Biology",
    "Mechanical Engineering",
    "People and Culture",
    "Project Management",
    "Psychology",
    "Public Relations",
    "Research and Development",
    "Robotics",
    "Science and Research",
    "Science and Technology",
    "Software Development",
    "Software Engineering",
    "Sports and Recreation",
    "Sustainability",
    "Technology and Engineering",
    "Telecommunications",
    "Urban Planning",
    "Veterinary Science",
    "Video Production",
    "Web Development"]

University = [
    "Australian Catholic University",
    "Australian National University",
    "Avondale University",
    "Bond University",
    "Central Queensland University",
    "Charles Darwin University",
    "Charles Sturt University",
    "Curtin University",
    "Deakin University",
    "Edith Cowan University",
    "Federation University Australia",
    "Flinders University",
    "Griffith University",
    "James Cook University",
    "La Trobe University",
    "Macquarie University",
    "Monash University",
    "Murdoch University",
    "Queensland University of Technology",
    "RMIT University",
    "Southern Cross University",
    "Swinburne University of Technology",
    "Torrens University Australia",
    "The University of Adelaide",
    "University of Canberra",
    "University of Divinity",
    "The University of Melbourne",
    "University of New England",
    "University of New South Wales",
    "The University of Newcastle",
    "The University of Notre Dame Australia",
    "The University of Queensland",
    "University of South Australia",
    "University of Southern Queensland",
    "University of the Sunshine Coast",
    "The University of Sydney",
    "University of Tasmania",
    "University of Technology Sydney",
    "The University of Western Australia",
    "University of Wollongong",
    "Victoria University",
    "Western Sydney University"
]
